name: diffusion_net
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - python=3.8
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - cudatoolkit=11.3
  - pytorch
  - pip:
    - joblib
    - numpy
    - pillow
    - plyfile
    - polyscope
    - potpourri3d
    - python-utils
    - robust-laplacian
    - scikit-learn
    - scipy
    - six
    - sklearn
    - threadpoolctl
    - tqdm
    - typing-extensions
